#!/bin/bash
# Script to build Salted Arch Linux iso files

set -e
customize=releng/airootfs/root/customize_airootfs.sh

display_help() {
	echo "
Script for making Arch Linux bootable ISO-files with preconfigured salt-entities.

Usage:
	./iso_make [option]

Options:
	master - make a salt-master iso-file
	minion - make a salt-minion iso-file
	
Example:
	./iso_make minion

Note: you need to be running Arch Linux with archiso and arch-install-scripts
installed. ISO-file is placed in out/ directory.
"
}

if ! [[ $1 =~ ^(master|minion)$ ]]; then display_help; exit; fi

root_check() {
	if [ $(id -u) != 0 ]; then
		echo "This script must be run as root."; exit
	fi
}

pwd_check() {
	if [[ $PWD != */archlive ]]; then
		echo "Make sure you are in the repository root."; exit
	fi
}

cleanup() {
	if [[ -d work ]]; then rm -rf work/; fi
}

# Do initial checks and preparations
root_check
pwd_check
chown root:root ./ -R
cleanup
cp -v $1_airootfs $customize

# Main build script, modified from archiso package
releng/build.sh -v

# Revert ownership back
chown tqre:tqre ./ -R

# Move the iso file somewhere if needed
# TODO: add command line argument for this
mv -v out/*.iso /home/tqre/Desktop/VBoxShare/$1.iso

# Comment this out to examine the built airootfs in work/
#cleanup


